name: AchievmentHunterTwo
main: me.EthanBilbrey.AchievmentHunterTwo.Main
version: 1.0
api-version: 1.16
author: Ethan Bilbrey
description: Complete custom achievments to win
commands:
   ahstart:
      usage: /<command>
      description: Starts challenges
   ahstop:
      usage: /<command>
      description: Stops challenges